I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1930, in script
    jump .giant_dmg
ScriptError: could not find label 'start_fight_2.giant_dmg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1930, in script
    jump .giant_dmg
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "D:\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start_fight_2.giant_dmg'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090405
Novel project 1.0
Tue Sep  6 21:39:45 2022
