I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1496, in script call
    call CardGame
  File "game/card_mg.rpy", line 28, in script
    python:
  File "game/card_mg.rpy", line 36, in <module>
    card_values.insert('empty')
TypeError: insert() takes exactly 2 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1496, in script call
    call CardGame
  File "game/card_mg.rpy", line 28, in script
    python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/card_mg.rpy", line 36, in <module>
    card_values.insert('empty')
  File "renpy/python.py", line 875, in do_mutation
    return method(self, *args, **kwargs)
TypeError: insert() takes exactly 2 arguments (1 given)

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Novel project 1.0
Sun Aug 28 21:07:27 2022
